# Generated by Django 4.2.9 on 2024-04-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('valor_atual', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lpa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vpa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pvp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('psr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EBITDA', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_ebitda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_operacional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pcf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('liquidez_corrente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('liquidez_imediata', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('liquidez_seca', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('giro_ativo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('endividamento_geral', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo_acao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divida_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('divida_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('capital_giro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receita_liquida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ebit_acao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_ebit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grahan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bazin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='BackEnd.ticket')),
            ],
        ),
    ]
