# Generated by Django 4.2.9 on 2024-04-07 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_ticket_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='setor',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketatualizacao',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizacoes', to='BackEnd.ticket'),
        ),
    ]
