# Generated by Django 5.2 on 2025-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_alter_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=1, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='setor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
